require 'dotenv/load'

INCOMING_WEBHOOK_URL = ENV['INCOMING_WEBHOOK_URL']
OUTGOING_WEBHOOK_TOKEN = ENV['OUTGOING_WEBHOOK_TOKEN']
BOT_ACCESS_TOKEN = ENV['BOT_ACCESS_TOKEN']
ADMIN_USERNAME = ENV['ADMIN_USERNAME'] || 'admin'
BOT_USERNAME = ENV['BOT_USERNAME'] || 'bot_username'
DEFAULT_CHANNEL_ID = ENV['DEFAULT_CHANNEL_ID'] || 'your_default_channel_id'
